// <auto-generated />
namespace Static_and_Login.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class SyncModeChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SyncModeChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202608200155557_SyncModeChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
